[package]
name = "rorm-db"
version = "0.9.1"
edition = "2021"
categories = ["database"]
keywords = ["async", "orm", "database", "orm"]
repository = "https://github.com/rorm-orm/rorm-db"
authors = ["myOmikron <git@omikron.dev>"]
homepage = "https://rorm.rs"
documentation = "https://docs.rorm.rs"
license = "MIT"
description = "The inner database abstraction layer from rorm."

[lib]
name = "rorm_db"

[dependencies]
rorm-sql = { version = "~0.8", path = "../rorm-sql" }
rorm-declaration = { version = "~0.4", path = "../rorm-declaration" }

# Stream trait
futures-core = "~0.3"

# Allow wrapping futures and streams
pin-project = { version = "~1" }

# SQL executor. Optional because it requires a runtime and a TLS implementation.
sqlx = { version = "~0.8", optional = true, default-features = false, features = ["json", "time", "chrono", "uuid", "runtime-tokio"] }

# Logging facade
log = { version = "~0.4" }

# Serialization
serde = { version = "~1", features = ["derive"], optional = true }

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.docs.rs]
features = ["all-driver", "serde", "tokio", "async-std", "native-tls", "rustls"]

[features]
all-driver = [
    "mysql",
    "postgres",
    "sqlite"
]

serde = [
    "dep:serde",
    "log/serde",
]

# database backends
mysql = [
    "sqlx/mysql",
    "rorm-sql/mysql",
    "rorm-declaration/mysql"
]
postgres = [
    "sqlx/postgres",
    "rorm-sql/postgres",
    "rorm-declaration/postgres"
]
sqlite = [
    "sqlx/sqlite",
    "rorm-sql/sqlite",
    "rorm-declaration/sqlite"
]

## Exclusive drivers
postgres-only = [
    "postgres",
    "rorm-sql/postgres-only",
    "sqlx/mac_address",
    "sqlx/ipnetwork",
    "sqlx/bit-vec",
]

# sqlx tls
rustls = [
    "sqlx/tls-rustls"
]
native-tls = [
    "sqlx/tls-native-tls"
]
